const filterDefaults = {
  enabled: true,
  delay: 0,
  except_releases: '',
  announce_types: [] as string[],
  resolutions: [] as string[],
  sources: [] as string[],
  match_categories: '',
  is_auto_updated: false,
  release_profile_duplicate: null,
  match_release_groups: '',
  except_release_groups: '',
} as const;

export const DEMO_FILTERS = [
  {
    name: 'fl-freeleech-high-priority',
    version: '1',
    _id: 'gen-freeleech-high',
    data: {
      ...filterDefaults,
      min_size: '1GB',
      max_size: '30GB',
      max_downloads: 5,
      max_downloads_unit: 'HOUR',
      freeleech: true,
      priority: 4,
      delay: 5,
    },
  },
  {
    name: 'fl-freeleech-medium-priority',
    version: '1',
    _id: 'gen-freeleech-medium',
    data: {
      ...filterDefaults,
      min_size: '1GB',
      max_size: '30GB',
      max_downloads: 3,
      max_downloads_unit: 'HOUR',
      freeleech: true,
      priority: 3,
      delay: 30,
    },
  },
  {
    name: 'fl-freeleech-low-priority',
    version: '1',
    _id: 'gen-freeleech-low',
    data: {
      ...filterDefaults,
      min_size: '1GB',
      max_size: '30GB',
      max_downloads: 2,
      max_downloads_unit: 'HOUR',
      freeleech: true,
      priority: 2,
      delay: 60,
    },
  },
  {
    name: 'fl-freeleech-opportunistic-priority',
    version: '1',
    _id: 'gen-freeleech-opportunistic',
    data: {
      ...filterDefaults,
      min_size: '1GB',
      max_size: '15GB',
      max_downloads: 1,
      max_downloads_unit: 'HOUR',
      freeleech: true,
      priority: 1,
      delay: 65,
    },
  },
];
