services:
  dynamodb-local:
    image: amazon/dynamodb-local@sha256:d89f8fcc6b1a39cb35976c248ed42a28c66ae00dc043099210f5571e42648ab4
    container_name: filterbrr-dynamodb
    user: root
    ports:
      - '8001:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /data'
    volumes:
      - dynamodb-data:/data

  localstack:
    image: localstack/localstack@sha256:cea732cdcc0982900b6b0c5c4fca6b90b54959708b2830366d5e11e98e71f6ee
    container_name: filterbrr-localstack
    ports:
      - '4567:4566'
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack-data:/var/lib/localstack
      - ./localstack-init:/etc/localstack/init/ready.d

  torrent-scraper-lambda:
    build:
      context: ./lambdas/torrent-scraper
      dockerfile: Dockerfile.dev
    container_name: filterbrr-torrent-scraper
    ports:
      - '9001:8080'
    volumes:
      - ./lambdas/torrent-scraper/src:/var/task/src
      - ./lambdas/torrent-scraper/esbuild.dev.mjs:/var/task/esbuild.dev.mjs
      - ./lambdas/torrent-scraper/esbuild.lambda.mjs:/var/task/esbuild.lambda.mjs
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - S3_BUCKET=filterbrr-userdata
      - AWS_ENDPOINT_URL=http://localstack:4566
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_LAMBDA_FUNCTION_TIMEOUT=900
    depends_on:
      - localstack

  filter-generator-lambda:
    build:
      context: ./lambdas/filter-generator
      dockerfile: Dockerfile.dev
    container_name: filterbrr-filter-generator
    ports:
      - '9002:8080'
    volumes:
      - ./lambdas/filter-generator/src:/var/task/src
      - ./lambdas/filter-generator/esbuild.dev.mjs:/var/task/esbuild.dev.mjs
      - ./lambdas/filter-generator/esbuild.lambda.mjs:/var/task/esbuild.lambda.mjs
      - ./packages/filter-engine:/var/task/node_modules/filter-engine
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - S3_BUCKET=filterbrr-userdata
      - AWS_ENDPOINT_URL=http://localstack:4566
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_LAMBDA_FUNCTION_TIMEOUT=900
    depends_on:
      - localstack

volumes:
  dynamodb-data:
  localstack-data:
