FROM public.ecr.aws/lambda/nodejs:22

WORKDIR /var/task

COPY package.json ./
RUN npm install

RUN npm install -g typescript nodemon

COPY tsconfig.json ./

ENTRYPOINT []

CMD ["sh", "-c", \
  "tsc 2>/dev/null || true; \
   tsc --watch --preserveWatchOutput & \
   nodemon --watch dist --delay 1 --signal SIGTERM \
     --exec '/lambda-entrypoint.sh dist/index.handler'"]
